### ISSUE TITLE
Update supported version number

### ISSUE THREAD

**Issue by Qeole** [tmatz/thunderbird-qfb-watched-addon#2]
Hi, I am successfully using your add-on on Thunderbird version 52 (to be precise: 52.2.1, on Linux), even though your `install.rdf` file indicates that the maximum supported version is 31. Might be worth updating it to help people find it on AMO.

And of course, thanks a lot for this add-on!

**Comment by tmatz** [comment]
Thank you for your advice!
install.rdf and AMO registration has been updated.

**Comment by Qeole** [comment]
Neat! Thanks
