### ISSUE TITLE
Impossible to support TB 68 

### ISSUE THREAD

**Issue by tmatz** [tmatz/thunderbird-qfb-watched-addon#5]
Legacy addons are no more supported by TB.
And also, TB does not provide custom quick filter feature by MailExtension.
So, it becomes impossible to support TB no more.

- https://thunderbird-webextensions.readthedocs.io/en/latest/

Bye.

**Comment by tmatz** [comment]
Finally I found the way to migrate to WebExtension.

Review process is in progress.

**Comment by tmatz** [comment]
merged #6

**Comment by tmatz** [comment]
Become not work after restart two times after install this extension.

**Comment by tmatz** [comment]
No, it doesn't work...

Quick filter toolbar button should be added **before** window.onload callback invoked. But it seems that TB 68 does not guarantee to invoke startup() of bootstrap extension before onload.

Maybe related: https://bugzilla.mozilla.org/show_bug.cgi?id=1603950

**Comment by tmatz** [comment]
request for qfb API: https://bugzilla.mozilla.org/show_bug.cgi?id=1607649

**Comment by tmatz** [comment]
WebExtension Experiments ? There seems to be a possibility.
https://thunderbird-webextensions.readthedocs.io/en/68/how-to/experiments.html

**Comment by tmatz** [comment]
reported bug about addon execution timing: https://bugzilla.mozilla.org/show_bug.cgi?id=1611880

**Comment by logological** [comment]
Has there been any further progress on this?  It would be great to see the add-on work with the latest stable version of Thunderbird.

**Comment by tmatz** [comment]
@logological Thank you for your interest.

But I've lost interest in this plugin anymore.

I've checked the current status of Thunderbird, but I haven't seen any progress in the extensibility of the quick filter bar.

I discontinued the development of this plugin.
